[meta]
name = "Altered Nadeo - Alt Map Picker"
author = "ar....."
category = "Altered Nadeo"
version = "3.0.0"
siteid = 483

[script]
dependencies = [ "NadeoServices" ]
exports = [ "src/Exports/Export.as" ]
