[meta]
name = "(dev)vt1 Altered Nadeo - Alt Map Picker"
author = "ar....."
category = "Altered Nadeo"
version = "2.2.0"
siteid = 483

[script]
dependencies = [ "NadeoServices" ]
exports = [ "src/Exports/Export.as" ]
