[meta]
name = "Altered Nadeo - Alt Map Picker"
author = "ar....."
category = "Altered Nadeo"
version = "0.1.1"

[script]
dependencies = [ "NadeoServices" ]
exports = ["src/Legacy/Exports/Export.as", "src/Exports/Export.as"]
